// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWijtPRTlk6WPnVvocHX1DRnbFITVRxA',
    appId: '1:495547438699:web:4840bd8bac19ebda8cc32e',
    messagingSenderId: '495547438699',
    projectId: 'first-app-19e2d',
    authDomain: 'first-app-19e2d.firebaseapp.com',
    storageBucket: 'first-app-19e2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeXv7VPNZineqsSBoo5sVnrDsmceiGK8',
    appId: '1:495547438699:android:208a1469e8f4a18b8cc32e',
    messagingSenderId: '495547438699',
    projectId: 'first-app-19e2d',
    storageBucket: 'first-app-19e2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMTE0pOT5oC-TTsRig2ez9M289o0n4XY0',
    appId: '1:495547438699:ios:f6f4d2a122441a7f8cc32e',
    messagingSenderId: '495547438699',
    projectId: 'first-app-19e2d',
    storageBucket: 'first-app-19e2d.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );
}
